Make formatting fixes a downloadable artifact

diff --git a/.github/workflows/make.yml b/.github/workflows/make.yml
--- a/.github/workflows/make.yml
+++ b/.github/workflows/make.yml
@@ -16,12 +16,21 @@ jobs:
       if: '!cancelled()'
       run: |
         clang-format -i */*.[ch]
-        if git diff | grep ""; then
-          (echo "Formatting errors detected by clang-format." \
-                "Please run \`make format\`.";
+        git diff > formatting-fixes.diff
+        if ! grep "" formatting-fixes.diff; then
+          rm -f formatting-fixes.diff
+        else
+          (echo "Formatting errors detected by clang-format. Please run" \
+                "\`make format\` or apply formatting-fixes.diff below.";
            echo) >> $GITHUB_STEP_SUMMARY
           false
         fi
+    - uses: actions/upload-artifact@v4
+      if: '!cancelled()'
+      with:
+        if-no-files-found: ignore
+        name: formatting-fixes.diff
+        path: formatting-fixes.diff
     - name: Check C89 compliance
       if: '!cancelled()'
       env:
